Test

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -5,131 +5,281 @@ notifications:
     on_success: always
 on_failure: always
 
-language: php
 
-sudo: true
+  postgresql: "9.6"
 
-dist: trusty
+env:
+    # Although we want to run these jobs and see failures as quickly as possible, we also want to get the slowest job to
+    # start first so that the total run time is not too high.
+    #
+    # We only run MySQL on PHP 7.2, so run that first.
+    # CI Tests should be second-highest in priority as these only take <= 60 seconds to run under normal circumstances.
+    # Postgres is significantly is pretty reasonable in its run-time.
 
-addons:
-  firefox: "47.0.1"
-  postgresql: "9.5"
-  apt:
-    packages:
-      - openjdk-8-jre-headless
+    # Run CI Tests without running PHPUnit.
+    - DB=none     TASK=CITEST
+
+    # Run unit tests on Postgres
+    - DB=pgsql    TASK=PHPUNIT
+
+    # Perform an upgrade test too.
+    - DB=pgsql    TASK=UPGRADE
+
+jobs:
+    # Enable fast finish.
+    # This will fail the build if a single job fails (except those in allow_failures).
+    # It will not stop the jobs from running.
+    fast_finish: true
+
+    include:
+          # Run mysql only on highest - it's just too slow
+        - php: 7.4
+          env: DB=mysqli   TASK=PHPUNIT
+          # Run grunt/npm install on highest version too ('node' is an alias for the latest node.js version.)
+        - php: 7.4
+          env: DB=none     TASK=GRUNT   NVM_VERSION='lts/carbon'
 
 cache:
-  directories:
-    - $HOME/.composer/cache
-    - $HOME/.npm
-
-matrix:
-  include:
-    - php: 7.1
-      env: 
-        DB=pgsql
-        MOODLE_BRANCH=MOODLE_33_STABLE
-        MOODLE_CI_VERSION=2
-    - php: 7.1
-      env: 
-        DB=mysqli
-        MOODLE_BRANCH=MOODLE_33_STABLE
-        MOODLE_CI_VERSION=2
-    - php: 7.1
-      env: 
-        DB=pgsql
-        MOODLE_BRANCH=MOODLE_34_STABLE
-        MOODLE_CI_VERSION=2
-    - php: 7.1
-      env: 
-        DB=mysqli
-        MOODLE_BRANCH=MOODLE_34_STABLE
-        MOODLE_CI_VERSION=2
-    - php: 7.1
-      env: 
-        DB=pgsql
-        MOODLE_BRANCH=MOODLE_35_STABLE
-        MOODLE_CI_VERSION=2
-    - php: 7.1
-      env: 
-        DB=mysqli
-        MOODLE_BRANCH=MOODLE_35_STABLE
-        MOODLE_CI_VERSION=2
-    - php: 7.1
-      env: 
-        DB=pgsql
-        MOODLE_BRANCH=MOODLE_36_STABLE
-        MOODLE_CI_VERSION=2
-    - php: 7.1
-      env: 
-        DB=mysqli
-        MOODLE_BRANCH=MOODLE_36_STABLE
-        MOODLE_CI_VERSION=2
-    - php: 7.1
-      env: 
-        DB=pgsql
-        MOODLE_BRANCH=MOODLE_37_STABLE
-        MOODLE_CI_VERSION=2
-    - php: 7.1
-      env: 
-        DB=mysqli
-        MOODLE_BRANCH=MOODLE_37_STABLE
-        MOODLE_CI_VERSION=2
-    - php: 7.1
-      env: 
-        DB=pgsql
-        MOODLE_BRANCH=MOODLE_38_STABLE
-        MOODLE_CI_VERSION=2
-    - php: 7.1
-      env: 
-        DB=mysqli
-        MOODLE_BRANCH=MOODLE_38_STABLE
-        MOODLE_CI_VERSION=2
-    - php: 7.2
-      env: 
-        DB=pgsql
-        MOODLE_BRANCH=master
-        MOODLE_CI_VERSION=2
-    - php: 7.2
-      env: 
-        DB=mysqli
-        MOODLE_BRANCH=master
-        MOODLE_CI_VERSION=2
+    directories:
+      - $HOME/.composer/cache
+      - $HOME/.npm
 
 before_install:
-  - phpenv config-rm xdebug.ini
-  - nvm install 8.9
-  - nvm use 8.9
-  - cd ../..
-  - if [[ $MOODLE_CI_VERSION == 1 ]];
-    then composer create-project -n --no-dev --prefer-dist blackboard-open-source/moodle-plugin-ci ci ^1;
-    else composer create-project -n --no-dev --prefer-dist blackboard-open-source/moodle-plugin-ci ci ^2;
-    fi
-  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"
+    - docker run -d -p 127.0.0.1:8080:80 --name exttests moodlehq/moodle-exttests
+    # Avoid IPv6 default binding as service (causes redis not to start).
+    - sudo service redis-server start --bind 127.0.0.1
 
 install:
-  - if [[ $MOODLE_CI_VERSION == 1 ]];
-    then
-      if [ -n $GITHUB_APITOKEN ]; then
-        cd ci;
-        composer config -g github-oauth.github.com $GITHUB_APITOKEN;
-        cd ..;
-      fi
-    fi
+    - >
+        if [ "$DB" = 'mysqli' ];
+        then
+            sudo mkdir /mnt/ramdisk
+            sudo mount -t tmpfs -o size=1024m tmpfs /mnt/ramdisk
+            sudo service mysql stop
+            sudo mv /var/lib/mysql /mnt/ramdisk
+            sudo ln -s /mnt/ramdisk/mysql /var/lib/mysql
+            sudo service mysql restart
+        fi
+    - >
+        if [ "$DB" = 'pgsql' ];
+        then
+            sudo mkdir /mnt/ramdisk
+            sudo mount -t tmpfs -o size=1024m tmpfs /mnt/ramdisk
+            sudo service postgresql stop
+            sudo mv /var/lib/postgresql /mnt/ramdisk
+            sudo ln -s /mnt/ramdisk/postgresql /var/lib/postgresql
+            sudo service postgresql start 9.6
+        fi
+    - >
+        if [ "$TASK" = 'PHPUNIT' ];
+        then
+            if [ -n "$GITHUB_APITOKEN" ]; then
+                composer config github-oauth.github.com $GITHUB_APITOKEN;
+                echo 'auth.json' >> .git/info/exclude
+            fi
 
-  - moodle-plugin-ci install
+            echo 'extension="redis.so"' > /tmp/redis.ini
+            phpenv config-add /tmp/redis.ini
+
+            # Install composer dependencies.
+            # We need --no-interaction in case we hit API limits for composer. This causes it to fall back to a standard clone.
+            # Typically it should be able to use the Composer cache if any other job has already completed before we started here.
+            travis_retry composer install --prefer-dist --no-interaction;
+        fi
+
+    - >
+        if [ "$TASK" = 'GRUNT' ];
+        then
+            nvm install $NVM_VERSION ;
+            nvm use $NVM_VERSION ;
+        fi
+
+before_script:
+    - phpenv config-rm xdebug.ini
+    - >
+      if [ "$TASK" = 'PHPUNIT' -o "$TASK" = 'UPGRADE' ];
+      then
+        # Copy generic configuration in place.
+        cp config-dist.php config.php ;
+
+        # Create the moodledata directory.
+        mkdir -p "$HOME"/roots/base
+
+        # The database name and password.
+        sed -i \
+          -e "s%= 'moodle'%= 'travis_ci_test'%" \
+          -e "s%= 'password'%= ''%" \
+          config.php ;
+
+        # The wwwroot and dataroot.
+        sed -i \
+          -e "s%http://example.com/moodle%https://localhost%" \
+          -e "s%/home/example/moodledata%/home/travis/roots/base%" \
+          config.php ;
+
+        if [ "$DB" = 'pgsql' ];
+        then
+          # Postgres-specific setup.
+          sed -i \
+            -e "s%= 'username'%= 'postgres'%" \
+            config.php ;
+
+          psql -c 'CREATE DATABASE travis_ci_test;' -U postgres;
+        fi
+
+        if [ "$DB" = 'mysqli' ];
+        then
+          # MySQL-specific setup.
+          sed -i \
+            -e "s%= 'pgsql'%= 'mysqli'%" \
+            -e "s%= 'username'%= 'travis'%" \
+            -e "s%=> 'utf8mb4_unicode_ci'%=> 'utf8mb4_bin'%" \
+            config.php;
+
+          mysql -u root -e 'SET GLOBAL innodb_file_format=barracuda;' ;
+          mysql -u root -e 'SET GLOBAL innodb_file_per_table=ON;' ;
+          mysql -u root -e 'SET GLOBAL innodb_large_prefix=ON;' ;
+          mysql -e 'CREATE DATABASE travis_ci_test DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_bin;' ;
+        fi
+      fi
+
+    - >
+      if [ "$TASK" = 'PHPUNIT' ];
+      then
+        # Create a directory for the phpunit dataroot.
+        mkdir -p "$HOME"/roots/phpunit
+
+        # The phpunit dataroot and prefix..
+        sed -i \
+          -e "/require_once/i \\\$CFG->phpunit_dataroot = '\/home\/travis\/roots\/phpunit';" \
+          -e "/require_once/i \\\$CFG->phpunit_prefix = 'p_';" \
+          config.php ;
+        # Enable test external resources
+        sed -i \
+          -e "/require_once/i \\define('TEST_EXTERNAL_FILES_HTTP_URL', 'http://127.0.0.1:8080');" \
+          -e "/require_once/i \\define('TEST_EXTERNAL_FILES_HTTPS_URL', 'http://127.0.0.1:8080');" \
+          config.php ;
+
+        # Redis cache store tests
+        sed -i \
+          -e "/require_once/i \\define('TEST_CACHESTORE_REDIS_TESTSERVERS', '127.0.0.1');" \
+          config.php ;
+        # Redis session tests, but not for PHP 7.2 and up. See MDL-60978 for more info.
+        redissession="define('TEST_SESSION_REDIS_HOST', '127.0.0.1');"
+        sed -i \
+          -e "/require_once/i \\${redissession}" \
+          config.php ;
+
+        # Initialise PHPUnit for Moodle.
+        php admin/tool/phpunit/cli/init.php
+      fi
+
+    - >
+      if [ "$TASK" = 'GRUNT' ];
+      then
+        npm install --no-spin;
+        npm install --no-spin -g grunt ;
+      fi
+
+    ########################################################################
+    # CI Tests
+    ########################################################################
+    - >
+      if [ "$TASK" = 'CITEST' ];
+      then
+        # Note - this is deliberately placed in the script section as we
+        # should not add any code until after phpunit has run.
+
+        # The following repositories are required.
+        # The local_ci repository does the actual checking.
+        git clone https://github.com/moodlehq/moodle-local_ci.git local/ci
+
+        # We need the official upstream for comparison
+        git remote add upstream https://github.com/moodle/moodle.git;
+
+        git fetch upstream MOODLE_38_STABLE;
+        export GIT_PREVIOUS_COMMIT="`git merge-base FETCH_HEAD $TRAVIS_COMMIT`";
+        export GIT_COMMIT="$TRAVIS_COMMIT";
+        export UPSTREAM_FETCH_HEAD=`git rev-parse FETCH_HEAD`
+
+        # Variables required by our linter.
+        export gitcmd=`which git`;
+        export gitdir="$TRAVIS_BUILD_DIR";
+        export phpcmd=`which php`;
+      fi
+
+    ########################################################################
+    # Upgrade test
+    ########################################################################
+    - >
+      if [ "$TASK" = 'UPGRADE' ];
+      then
+        # We need the official upstream.
+        git remote add upstream https://github.com/moodle/moodle.git;
+
+        # Checkout 30 STABLE branch (the first version compatible with PHP 7.x)
+        git fetch upstream MOODLE_30_STABLE;
+        git checkout MOODLE_30_STABLE;
+
+        # Perform the upgrade
+        php admin/cli/install_database.php --agree-license --adminpass=Password --adminemail=admin@example.com --fullname="Upgrade test" --shortname=Upgrade;
+
+        # Return to the previous commit
+        git checkout -;
+
+        # Perform the upgrade
+        php admin/cli/upgrade.php --non-interactive --allow-unstable ;
+
+        # The local_ci repository can be used to check upgrade savepoints.
+        git clone https://github.com/moodlehq/moodle-local_ci.git local/ci ;
+      fi
 
 script:
-  - moodle-plugin-ci phplint
-  - moodle-plugin-ci phpcpd
-  - moodle-plugin-ci phpmd
-  - moodle-plugin-ci codechecker
-  - moodle-plugin-ci validate
-  - if [[ $MOODLE_CI_VERSION == 2 ]];
-    then
-      moodle-plugin-ci savepoints;
-      moodle-plugin-ci mustache;
-      moodle-plugin-ci grunt;
-    fi
-  - moodle-plugin-ci phpunit
-  - moodle-plugin-ci behat
+    - >
+      if [ "$TASK" = 'PHPUNIT' ];
+      then
+        vendor/bin/phpunit --fail-on-risky --disallow-test-output --verbose;
+      fi
+
+    - >
+      if [ "$TASK" = 'CITEST' ];
+      then
+        bash local/ci/php_lint/php_lint.sh;
+      fi
+
+    - >
+      if [ "$TASK" = 'GRUNT' ];
+      then
+        grunt ;
+        # Add all files to the git index and then run diff --cached to see all changes.
+        # This ensures that we get the status of all files, including new files.
+        # We ignore npm-shrinkwrap.json to make the tasks immune to npm changes.
+        git add . ;
+        git reset -- npm-shrinkwrap.json ;
+        git diff --cached --exit-code ;
+      fi
+
+    ########################################################################
+    # Upgrade test
+    ########################################################################
+    - >
+      if [ "$TASK" = 'UPGRADE' ];
+      then
+        cp local/ci/check_upgrade_savepoints/check_upgrade_savepoints.php ./check_upgrade_savepoints.php
+        result=`php check_upgrade_savepoints.php`;
+        # Check if there are problems
+        count=`echo "$result" | grep -P "ERROR|WARN" | wc -l` ;
+        if (($count > 0));
+        then
+          echo "$result"
+          exit 1 ;
+        fi
+      fi
+
+after_script:
+    - >
+      if [ "$TASK" = 'PHPUNIT' ];
+      then
+        EXTTESTS_HITS=$(docker logs exttests 2>&1 | grep -Fv -e 'AH00558' -e '[pid 1]' | wc -l)
+        echo -e "\nTest local resources number of hits: ${EXTTESTS_HITS}.\n"
+      fi
